export const generateTimesheetEmailTemplate = (user, timesheet, weekRange) => {
  const formatDate = (date) => new Date(date).toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  const calculateTotalHours = (entries) => {
    return entries.reduce((total, entry) => total + (entry.hoursWorked || 0), 0);
  };

  const totalHours = calculateTotalHours(timesheet.entries);

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Weekly Timesheet - ${weekRange}</title>
      <style>
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          background-color: #f5f5f5;
        }
        .container {
          background-color: white;
          padding: 30px;
          border-radius: 10px;
          box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
          text-align: center;
          border-bottom: 3px solid #007bff;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .header h1 {
          color: #007bff;
          margin: 0;
          font-size: 28px;
        }
        .user-info {
          background-color: #f8f9fa;
          padding: 15px;
          border-radius: 5px;
          margin-bottom: 20px;
        }
        .summary {
          background-color: #e3f2fd;
          padding: 15px;
          border-radius: 5px;
          margin-bottom: 20px;
        }
        .summary h3 {
          margin-top: 0;
          color: #1976d2;
        }
        .day-entry {
          border: 1px solid #ddd;
          border-radius: 5px;
          margin-bottom: 15px;
          overflow: hidden;
        }
        .day-header {
          background-color: #007bff;
          color: white;
          padding: 10px 15px;
          font-weight: bold;
        }
        .day-content {
          padding: 15px;
        }
        .task-item {
          background-color: #f8f9fa;
          padding: 10px;
          margin-bottom: 8px;
          border-radius: 3px;
          border-left: 3px solid #007bff;
        }
        .task-title {
          font-weight: bold;
          color: #333;
        }
        .task-description {
          color: #666;
          font-size: 14px;
          margin-top: 5px;
        }
        .hours {
          color: #007bff;
          font-weight: bold;
        }
        .footer {
          text-align: center;
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #ddd;
          color: #666;
          font-size: 14px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>📊 Weekly Timesheet</h1>
          <p><strong>${weekRange}</strong></p>
        </div>

        <div class="user-info">
          <h3>👤 Employee Information</h3>
          <p><strong>Name:</strong> ${user.name}</p>
          <p><strong>Email:</strong> ${user.email}</p>
        </div>

        <div class="summary">
          <h3>📈 Weekly Summary</h3>
          <p><strong>Total Hours Worked:</strong> ${totalHours.toFixed(2)} hours</p>
          <p><strong>Days Tracked:</strong> ${timesheet.entries.length} days</p>
          <p><strong>Average Daily Hours:</strong> ${(totalHours / timesheet.entries.length).toFixed(2)} hours</p>
        </div>

        <h3>📅 Daily Breakdown</h3>
        ${timesheet.entries.map(entry => `
          <div class="day-entry">
            <div class="day-header">
              ${formatDate(entry.date)} - ${entry.hoursWorked.toFixed(2)} hours
            </div>
            <div class="day-content">
              ${entry.activities.map(activity => `
                <div class="task-item">
                  <div class="task-title">${activity.taskTitle}</div>
                  ${activity.description ? `<div class="task-description">${activity.description}</div>` : ''}
                </div>
              `).join('')}
              ${entry.notes ? `<p><strong>Notes:</strong> ${entry.notes}</p>` : ''}
            </div>
          </div>
        `).join('')}

        <div class="footer">
          <p>This timesheet was automatically generated by Nexus Task Management System</p>
          <p>Generated on: ${new Date().toLocaleString()}</p>
        </div>
      </div>
    </body>
    </html>
  `;
};
